### PR TITLE
Resolve RuntimeException "Could not delete file"

### LINKED ISSUE #111: RuntimeException: Could not delete file after upgrade to 5.1.2
After updating to version 5.1.2, the following error occurs from time to time:
```
  [RuntimeException]                                                                                                                                 
  Could not delete ...
```

**Pre-requisites**
PHP: 8.2
composer: 2.2

**To Reproduce**
Please use the files below:
`composer.json`
```
{
    "config": {
        "allow-plugins": {
            "vaimo/composer-patches": true,
            "php-http/discovery": true
        }
    },
    "require": {
        "smile/elasticsuite": "2.11.4.2",
        "vaimo/composer-patches": "5.1.2"
    },
    "replace": {
        "magento/framework": "*",
        "magento/module-store": "*",
        "magento/module-backend": "*",
        "magento/module-catalog": "*",
        "magento/module-catalog-search": "*",
        "magento/module-catalog-graph-ql": "*",
        "magento/module-inventory-sales-api": "*",
        "magento/module-inventory-sales": "*",
        "magento/magento-composer-installer": "*",
        "magento/module-inventory-indexer": "*"
    },
    "extra": {
        "patches-file": "patches.json"
    }
}
```
`patches.json`
```
{
  "smile/elasticsuite": {
    "Test patch": "patch.patch"
  }
}
```
`patch.patch`
```
--- a/src/module-elasticsuite-core/etc/adminhtml/di.xml
+++ b/src/module-elasticsuite-core/etc/adminhtml/di.xml
@@ -21,7 +21,6 @@
     <type name="Magento\Framework\Notification\MessageList">
         <arguments>
             <argument name="messages" xsi:type="array">
-                <item name="elasticsuite" xsi:type="string">Smile\ElasticsuiteCore\Model\System\Message\NotificationAboutVersions</item>
                 <item name="elasticsuite_cluster_replicas_misconfig_warning" xsi:type="string">Smile\ElasticsuiteCore\Model\System\Message\WarningAboutClusterReplicasMisconfig</item>
             </argument>
         </arguments>
```
Sometimes it doesn't reproduce the first time you execute `composer install`, so execute the following command until it does:
```
rm -rf vendor/smile && composer install
```

**Expected**
The patch must be applied.

**Actual**
From time to time, a RuntimeException appears
e.g.
```
  [RuntimeException]                                                                                                                                 
  Could not delete /vendor/smile/elasticsuite/src/module-elasticsuite-core/view/adminhtml/web/images:  
```

**Notes**
The previous version (5.1.1) works properly, so we're using it for now.

### PR DESCRIPTION
**Pull request by bogdan-soroka-monsoonconsulting**
Fixes #111

### CODE REVIEW

**Comment by fredden** [comment]
This looks like it will revert at least part of https://github.com/vaimo/composer-patches/pull/107 which was created to fix #103. I can't see any explanation in #107 nor here to help me understand why this is the correct approach, and there's no reference to #103 here so I'm unsure if that's been taken into account. There don't seem to be any changes to the test-suite here to confirm that this change fixes the intended bug and does not break any other functionality. @bogdan-soroka-monsoonconsulting please can you provide some more information about this change?

**Comment by bogdan-soroka-monsoonconsulting** [comment]
Hi @fredden, Long story short:
- in version 5.1.1: downloading and installing the package occur simultaneously after uninstalling (unzip sometimes starts before a package has been downloaded #103)
- in version 5.2.2: uninstalling and installing the package occur simultaneously (large modules sometimes cannot be uninstalled before the installation starts #111)
- in this pull request: first uninstall the package, then download it, and only then install it

**Comment by fredden** [comment]
Thanks for the explanation. The original code looks like it does "uninstall, then download, then install." I guess the promise library used treats two consecutive `->then()` calls as "run in parallel," not "run in sequence."

**Comment by fredden** [comment]
@zamoroka-vaimo or @zamoroka, please can merge this in and tag a new release? This module cannot patch itself, so we can't apply this like bug-fixes for other packages.

**Comment by fredden** [comment]
> This module cannot patch itself

Technically it can patch itself, but the bug in question is most likely to happen the first time that we run `composer install` for a project (like in our CI pipeline where we start with a fresh checkout from version control). By the time the new code is written to the filesystem, PHP has already read the old files and has the old code running in memory. Subsequent times that Composer runs, the new/patched code is used.

**Review by zamoroka-vaimo — APPROVED** [review]

**Comment by zamoroka-vaimo** [comment]
added to 5.2.0 https://github.com/vaimo/composer-patches/releases/tag/5.2.0
Thanks for your contribution 🙌

**Pull request merged**
