### PR TITLE
[WIP] Started working on composer v2 support

### PR DESCRIPTION
**Pull request by hostep**
This is (or was) an attempt at making this module compatible with composer v2 in scope of https://github.com/vaimo/composer-patches/issues/59

However, I think I will give up on this, I'm not familiar enough with the codebase or with composer's internals.
Maybe the changes in here can be useful in case somebody else wants to pick this up later...

Remarks:
- PR was created from the `release/3` branch since I'm using macOs and only on that branch the built-in unit tests seems to be running without many issues (maybe those commits could be merged in `master` one day?)
- I temporarily removed the dependency on `vaimo/composer-changelogs` since that one also doesn't support composer v2 yet: https://github.com/vaimo/composer-changelogs/issues/3
- It's very difficult to keep supporting both composer v1 and v2 due to many internal calls to the composer source which have changed significantly between v1 and v2. Therefore I only declared the module as compatible with v2
- I got a bunch of tests working when executing `composer code:test` but unfortunately not all of them
- All changes I present in here should be investigated, I only tried to make the code run without errors but didn't check if it actually executed what it is supposed to execute since I'm not familiar with how composer works internally
- These changes will probably warrant a major v5 version as they are not backwards compatible with composer v1

Hoping that the work done in here is useful to the next person who attempts this 🙂

### CODE REVIEW

**Comment by allanpaiste** [comment]
Hey there! Very cool to see this being picked up by someone. I'll snoop around on how many of the functions actually changed to assess if we can get away without needing to do a full major release, but I'll def be chipping in on this one :)

**Comment by mbernabeu** [comment]
Please can we prioritize this issue, with the release of 2.4.2 it is a must-have.

**Comment by hostep** [comment]
@mbernabeu is probably talking about Magento 2.4.2, but this module isn't only used in Magento installations, it can be used in basically any php project using composer.

But indeed, having a composer v2 compatible version available for this module is the only thing which blocks us as well to move to composer v2 for our Magento projects. Even for [older Magento versions](https://gist.github.com/hostep/26de0bf2bb695eb3b6d51858c2e4562e).

Thanks for considering to help with this @allanpaiste! 🙂

**Review by allanpaiste — APPROVED** [review]

**Comment by allanpaiste** [comment]
Have now a fully functional version @ https://github.com/vaimo/composer-patches/pull/67

Have to do some cleanup still, but tests pass, patches apply, fun.

I think we can get away without having to release new major :)

**Comment by hostep** [comment]
Awesome work @allanpaiste!

I agree with not needing a new major version if the plugin keeps working fine with composer v1.

Thanks so much! 🙂

**Pull request merged**
