### PR TITLE
Fix #47 strpos() empty needle error

### LINKED ISSUE #47: Empty needle
When we tried to uninstall Klarna on our M2.3.3 project, we got an exception strpos() Empty Needle. We made a patch here, just in case $item was blank/null we returned false: \Vaimo\ComposerPatches\Package\ConfigAnalyser::ownsNamespace

**Expected**
No error when running composer functions

**Actual**
`$aja project remove-module klarna/m2-checkout
Dependency "composer/composer" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)            
Package operations: 0 installs, 1 update, 8 removals
  - Removing phpxmlrpc/phpxmlrpc (4.4.1)
Removing Phpxmlrpc/Phpxmlrpc
  [ErrorException]        
  strpos(): Empty needle  `

**Notes**
I didn't figure out What caused a blank $item in that function...

### PR DESCRIPTION
**Pull request by pierrotevrard-idp**

### CODE REVIEW

**Comment by allanpaiste** [comment]
@v-r 

Would be nice to backport this to 3.x as well

**Comment by pierrotevrard-idp** [comment]
@allanpaiste Do this project still alive, pls?

**Comment by allanpaiste** [comment]
I lost my chance to maintain it some time ago but I'm back now :)

**Comment by robertsplorins** [comment]
Had this issue too, would be nice if this could be merged

**Pull request merged**
